services:
  - type: web
    name: indobid
    runtime: node
    plan: starter
    buildCommand: npm install && npx prisma db push && npm run db:seed && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
